# See the `.packit/README.md` for details.

# The used RPM spec file path.
# A minimal RPM spec file to run the tests.
specfile_path: .packit/simde.spec

jobs:
  - &copr
    # Use Fedora COPR in the CI.
    # https://packit.dev/docs/configuration/#copr_build
    job: copr_build
    trigger: pull_request
    # Enable internet access in the COPR.
    enable_net: true
    # Executed targets in the CI. Available targets are below.
    # https://packit.dev/docs/configuration/#available-copr-build-targets
    #
    # Note that we keep the Fedora rawhide. See the `.packit/README.md` -
    # "Motivation and context" for details.
    targets:
      - fedora-rawhide-x86_64
      - fedora-rawhide-aarch64
      - fedora-rawhide-ppc64le
      - fedora-rawhide-s390x
  - <<: *copr
    # Run on push to any branch.
    trigger: commit
    # Run except the "master*" and "dependabot*" branches.
    # https://github.com/packit/packit/issues/1986
    branch: '(?!master)(?!dependabot)'
