FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y gcc-9-powerpc64le-linux-gnu g++-powerpc64le-linux-gnu qemu-user-static cmake binfmt-support
COPY . /simde
WORKDIR /simde
RUN mkdir -p test/build_s390x
WORKDIR /simde/test/build_s390x
RUN CC=/usr/bin/powerpc64le-linux-gnu-gcc-9 CXX=/usr/bin/powerpc64le-linux-gnu-g++-9 cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_C_FLAGS="-Wall -Wextra -Werror -mcpu=power8" -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror -mcpu=power8" ../ && \
  make -j$(nproc)
RUN QEMU_LD_PREFIX=/usr/powerpc64le-linux-gnu/ /usr/bin/qemu-ppc64le-static ./run-tests
