FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y gcc-9-s390x-linux-gnu g++-9-s390x-linux-gnu qemu-user-static cmake binfmt-support
COPY . /simde
WORKDIR /simde
RUN mkdir -p test/build_s390x
WORKDIR /simde/test/build_s390x
RUN CC=/usr/bin/s390x-linux-gnu-gcc-9 CXX=/usr/bin/s390x-linux-gnu-g++-9 cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_C_FLAGS="-Wall -Wextra -Werror" -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror" ../ && \
  make -j$(nproc)
RUN QEMU_LD_PREFIX=/usr/s390x-linux-gnu/ /usr/bin/qemu-s390x-static ./run-tests
