name: Lint GitHub Actions workflows
on: [push, pull_request]

permissions: {}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Check workflow files
        uses: kjanat/actionlint@662318dd6bbd9c0c120e35b03168bc1be69bf428 # v1.16.1
