name: Lint GitHub Actions workflows
on: [push, pull_request]

permissions: {}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Check workflow files
        uses: kjanat/actionlint@1ab487e641ac26ed42a8a753158033d55eaae2e4 # v1.14.0
