name: CI

on:
  push:
    branches-ignore:
      - 'ci/**'
      - '!ci/gha**'
      - 'dependabot/**'
  pull_request:
    branches:
      - 'master'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  native-aliases:
    runs-on: ubuntu-24.04
    env:
      CFLAGS: -DSIMDE_ENABLE_NATIVE_ALIASES -DSIMDE_NATIVE_ALIASES_TESTING -Wall -Wextra -Werror
      CXXFLAGS: -DSIMDE_ENABLE_NATIVE_ALIASES -DSIMDE_NATIVE_ALIASES_TESTING -Wall -Wextra -Werror
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: CPU Information
      run: cat /proc/cpuinfo
    - name: Install APT Dependencies
      run: |
        sudo apt-get update && \
        sudo apt-get -y --no-install-recommends install libxml2-utils ninja-build pipx && \
        pipx install meson==0.55.1
    - name: Convert
      run: ./test/native-aliases.sh
    - name: Configure
      run: meson setup build
    - name: Build
      run: ninja -C build -v
    - name: Test
      run: ninja -C build -v test

  arm64-native-aliases:
    runs-on: macos-15
    env:
      CFLAGS: -DSIMDE_ENABLE_NATIVE_ALIASES -DSIMDE_NATIVE_ALIASES_TESTING -Wall -Wextra -Werror -Wno-complex-component-init -Wno-poison-system-directories
      CXXFLAGS: -DSIMDE_ENABLE_NATIVE_ALIASES -DSIMDE_NATIVE_ALIASES_TESTING -Wall -Wextra -Werror -Wno-complex-component-init -Wno-poison-system-directories
      DEVELOPER_DIR:  /Applications/Xcode_16.0.app
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Compiler version
      run: cc --version
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}
    - name: Python install bug workaround # https://github.com/actions/setup-python/issues/577
      run: |
          find /usr/local/bin -type l -exec sh -c 'readlink -f "$1" \
          | grep -q ^/Library/Frameworks/Python.framework/Versions/' _ {} \; -exec rm -v {} \;
    - name: Install Homebrew Dependencies
      run: brew install meson ninja grep gnu-sed
    - name: Convert
      run: PATH="$HOMEBREW_PREFIX/opt/grep/libexec/gnubin:$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnubin:$PATH" bash -ex ./test/native-aliases.sh
    - name: Configure
      run: meson setup build
    - name: Build
      run: ninja -C build -v
    - name: Test
      run: ninja -C build -v test

